const catalogue = [
    {
      id: 1,
      name: "milk-cheese-egg",
      category: "milk-cheese-egg",
      description: "Молоко, сыр, яйцо",
      image: "assets/images/category/milk-cheese-egg.png",
    },
    {
      id: 2,
      name: "bread",
      category: "bread",
      description: "Хлеб",
      image: "assets/images/category/bread.png",
    },
    {
      id: 3,
      name: "fruits-vegetables",
      category: "fruits-vegetables",
      description: "Фрукты и овощи",
      image: "assets/images/category/fruits-vegetables.png",
    },
    {
      id: 4,
      name: "frozen-foods",
      category: "frozen-foods",
      description: "Замороженные продукты",
      image: "assets/images/category/frozenfood.png",
    },
    {
      id: 5,
      name: "drinks",
      category: "drinks",
      description: "Напитки",
      image: "assets/images/category/drinks.png",
    },
    {
      id: 6,
      name: "conditory",
      category: "conditory",
      description: "Кондитерские изделия",
      image: "assets/images/category/conditory.png",
    },
    {
      id: 7,
      name: "bakaleriya",
      category: "bakaleriya",
      description: "Бакалея",
      image: "assets/images/category/bakaleriya.png",
    },
    {
      id: 8,
      name: "healthy-eat",
      category: "healthy-eat",
      description: "Здоровое питание",
      image: "assets/images/category/healthy-eat.png",
    },
    {
      id: 9,
      name: "zoo-product",
      category: "zoo-product",
      description: "Зоотовары",
      image: "assets/images/category/zoo-product.png",
    },
    {
      id: 10,
      name: "child-eat",
      category: "child-eat",
      description: "Детское питание",
      image: "assets/images/category/child-eat.png",
    },
    {
      id: 11,
      name: "meat-chicken-sausage",
      category: "meat-chicken-sausage",
      description: "Мясо, птица, колбаса",
      image: "assets/images/category/meat-chicken-sausage.png",
    },
    {
      id: 12,
      name: "others",
      category: "others",
      description: "Непродовольственные товары",
      image: "assets/images/category/others.png",
    },
]